// Re-export all hooks for convenience
export { useAuth } from './useAuth'
export { useProfile, useProfileByUsername, useProfileStats, useCheckUsername } from './useProfile'
export { useTrending, useSearchMovies, useMovieDetails, usePopularMovies, useTopRatedMovies, TMDBService } from './useMovies'
export { useWatchlist, useIsInWatchlist } from './useWatchlist'
export { useFollow, useIsFollowing, useFollowMutations } from './useFollow'
export { useRating, useUserRatings } from './useRating'
export { useFollowingActivity } from './useActivity'
export { useAllWatchlists, useWatchlistLikeMutations } from './useWatchlists'
export { useUnreadActivityCount } from './useUnreadActivity'
